services:
  # Rails API Web Service
  - type: web
    name: kindred-api
    env: ruby
    region: oregon
    plan: free
    buildCommand: bundle install
    startCommand: bundle exec rails server -b 0.0.0.0 -p $PORT
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        value: 4f44675bbeb3557fc25102bc1f1aff62
